# Generated by Django 5.2.4 on 2025-07-10 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='assigned_to',
            field=models.ManyToManyField(related_name='homeworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
