# Generated by Django 5.2.4 on 2025-07-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homework_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworktask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
