# Generated by Django 5.2.4 on 2025-07-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_homeworktask_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='deadline',
        ),
    ]
