# Generated by Django 5.2.4 on 2025-07-12 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_remove_homework_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworktask',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworktask',
            name='task_type',
            field=models.CharField(choices=[('catatan', 'Catatan'), ('quiz', 'Quiz')], max_length=10),
        ),
    ]
