# Generated by Django 5.2.4 on 2025-07-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_homeworktask_posted_at_alter_homeworktask_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='created_at',
        ),
    ]
